ibmmq-source=kamelet:kamelet-studio-ibmmq-source
ibmmq-sink=kamelet:kamelet-studio-ibmmq-sink
ibmmq.queue=IBMMQ.INBOUND.Q
ibmmq.channel=DEV.ADMIN.SVRCONN
ibmmq.sslciphersuite=TLS_RSA_WITH_AES_128_CBC_SHA256
ibmmq.keystorepath=/home/pratyush/software/jbang-eip-builder/infra-setup/certs/ibmmq/clientkey.p12
ibmmq.keystorepassword=clientpassword
ibmmq.truststorepath=/home/pratyush/software/jbang-eip-builder/infra-setup/certs/ibmmq/clienttrust.p12
ibmmq.truststorepassword=mqpassword
