# Mock Profile - pure offline, no dependencies
quarkus.camel.stub.enabled=true
mongodb.uri=stub
ibmmq.host=stub
kafka.bootstrap-servers=stub

# Audit settings
audit.exclude.payload=false
APP_ENV=mock
APP_VERSION=1.0.0-SNAPSHOT
