# Dev Profile - connected to enterprise dev environment
ibmmq.host=dev-mq.corp.internal
ibmmq.ssl.enabled=true
ibmmq.ssl.cipher=TLS_RSA_WITH_AES_256_CBC_SHA256
ibmmq.ssl.keystore.path=/etc/certs/mq-client.jks
ibmmq.ssl.keystore.password=${env.MQ_KS_PASS}
ibmmq.ssl.truststore.path=/etc/certs/mq-truststore.jks
ibmmq.ssl.truststore.password=${env.MQ_TS_PASS}

mongodb.uri=mongodb+srv://dev-mongo.corp.internal

APP_ENV=dev
APP_VERSION=1.0.0-SNAPSHOT
