# DevServices Profile - uses local Docker containers
quarkus.mongodb.devservices.enabled=true
quarkus.artemis.devservices.enabled=true
quarkus.kafka.devservices.enabled=true

APP_ENV=devservices
APP_VERSION=1.0.0-SNAPSHOT
