apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: kamelet-studio-ibmmq-source
  labels:
    camel.apache.org/kamelet.type: "source"
  annotations:
    camel.apache.org/kamelet.title: "Kamelet Studio IBM MQ Source"
    camel.apache.org/kamelet.version: "1.0.0"
spec:
  definition:
    title: "Kamelet Studio IBM MQ Source"
    description: "Consumes messages from IBM MQ with SSL, mTLS, and Kerberos support."
    required:
      - queuename
    type: object
    properties:
      queuename:
        type: string
      hostname:
        type: string
        default: "localhost"
      port:
        type: integer
        default: 1414
      queuemanager:
        type: string
        default: "QM1"
      channel:
        type: string
        default: "DEV.APP.SVRCONN"
      username:
        type: string
        default: ""
      password:
        type: string
        format: password
        default: ""
      sslciphersuite:
        type: string
        default: ""
      sslpeername:
        type: string
        default: ""
      sslfipsrequired:
        type: boolean
        default: false
      transporttype:
        type: integer
        default: 1
      truststorepath:
        type: string
        default: ""
      truststorepassword:
        type: string
        format: password
        default: ""
      keystorepath:
        type: string
        default: ""
      keystorepassword:
        type: string
        format: password
        default: ""
      maxconnections:
        type: integer
        default: 5
      idletimeout:
        type: integer
        default: 30000
  template:
    beans:
      - name: sslFactory
        type: "#class:com.tessera.kameletstudio.core.lib.crypto.KameletStudioSslSocketFactory"
        properties:
          trustStorePath: '{{truststorepath}}'
          trustStorePassword: '{{truststorepassword}}'
          keyStorePath: '{{keystorepath}}'
          keyStorePassword: '{{keystorepassword}}'
      - name: mqConnectionFactory
        type: "#class:com.ibm.mq.jakarta.jms.MQConnectionFactory"
        properties:
          hostName: '{{hostname}}'
          port: '{{port}}'
          queueManager: '{{queuemanager}}'
          channel: '{{channel}}'
          sslCipherSuite: '{{sslciphersuite}}'
          sslSocketFactory: '#bean:{{sslFactory}}'
          sslPeerName: '{{sslpeername}}'
          sslFipsRequired: '{{sslfipsrequired}}'
          userName: '{{username}}'
          password: '{{password}}'
          transportType: '{{transporttype}}'
      - name: mqPoolFactory
        type: "#class:org.messaginghub.pooled.jms.JmsPoolConnectionFactory"
        properties:
          connectionFactory: '#bean:{{mqConnectionFactory}}'
          maxConnections: '{{maxconnections}}'
          connectionIdleTimeout: '{{idletimeout}}'
    from:
      uri: "jms:queue:{{queuename}}"
      parameters:
        connectionFactory: "#bean:{{mqPoolFactory}}"
      steps:
        - to: "kamelet:sink"
