apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: kamelet-studio-mongodb-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
  annotations:
    camel.apache.org/kamelet.title: "Kamelet Studio MongoDB Sink"
    camel.apache.org/kamelet.version: "1.0.0"
spec:
  definition:
    title: "Kamelet Studio MongoDB Sink"
    description: "Inserts or updates documents in a MongoDB collection."
    required:
      - database
      - collection
    type: object
    properties:
      connectionBean:
        type: string
        default: "mongoClient"
      database:
        type: string
      collection:
        type: string
      operation:
        type: string
        default: "insert"
        enum: [ "insert", "save", "update" ]
  template:
    from:
      uri: "kamelet:source"
      steps:
        - to: "mongodb:{{connectionBean}}?database={{database}}&collection={{collection}}&operation={{operation}}"
