import React, { useState } from 'react';
import { Route, Save, Download, Eye, Play, Trash2 } from 'lucide-react';
import Palette from './components/Palette';
import FlowCanvas from './components/FlowCanvas';
import PropertiesPanel from './components/PropertiesPanel';

function App() {
  const [selectedNode, setSelectedNode] = useState(null);

  const handleSave = () => {
    alert('Route saved as YAML DSL successfully!');
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob(["# Camel YAML DSL generated by Tessera Visual Designer\n- route:\n    from:\n      uri: timer:tick\n      steps:\n        - log: hello"], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "route.camel.yaml";
    document.body.appendChild(element);
    element.click();
  };

  return (
    <div className="flex flex-col h-screen bg-slate-950 text-slate-200 overflow-hidden font-sans">
      {/* Header / Toolbar */}
      <header className="h-14 border-b border-slate-800 bg-slate-900/50 flex items-center justify-between px-6 z-20">
        <div className="flex items-center gap-3">
          <div className="bg-blue-600 p-1.5 rounded-lg shadow-lg shadow-blue-500/20">
            <Route className="h-5 w-5 text-white" />
          </div>
          <div>
            <h1 className="text-sm font-bold tracking-tight">Tessera Visual Route Designer</h1>
            <p className="text-[10px] text-slate-500 font-medium uppercase tracking-widest">Chapter 17: Visual Pipeline Composer</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button 
            onClick={handleSave}
            className="flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-md text-xs font-semibold transition-all"
          >
            <Save className="h-3.5 w-3.5" />
            Save
          </button>
          <button 
            onClick={handleDownload}
            className="flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-md text-xs font-semibold transition-all"
          >
            <Download className="h-3.5 w-3.5" />
            Download YAML
          </button>
          <div className="w-px h-6 bg-slate-800 mx-2" />
          <button className="flex items-center gap-2 px-4 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-md text-xs font-bold shadow-lg shadow-blue-500/20 transition-all">
            <Play className="h-3.5 w-3.5 fill-current" />
            Run Route
          </button>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="flex-1 flex overflow-hidden">
        {/* Left: Palette */}
        <Palette />

        {/* Center: Canvas */}
        <FlowCanvas onNodeSelect={setSelectedNode} />

        {/* Right: Properties */}
        <PropertiesPanel selectedNode={selectedNode} />
      </main>

      {/* Footer / Status Bar */}
      <footer className="h-8 border-t border-slate-800 bg-slate-900 flex items-center justify-between px-4 text-[10px] text-slate-500 z-20">
        <div className="flex items-center gap-4">
          <span className="flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-emerald-500" />
            IDE Engine: Ready
          </span>
          <span>Zoom: 100%</span>
        </div>
        <div className="flex items-center gap-3">
          <span>Portable Component Mode</span>
          <span className="bg-slate-800 px-2 py-0.5 rounded border border-slate-700">v0.1.0-alpha</span>
        </div>
      </footer>
    </div>
  );
}

export default App;
