#Standardized Tessera Workspace Configuration - Automatically Updated to Absolute Paths
#Mon Jun 01 22:05:01 IST 2026
API_URL=http\://localhost\:8080
DRAWINGS_DIR=/home/pratyush/software/jbang-eip-builder/test-project-workspace/diagrams
FAKER_DB_DIR=/home/pratyush/software/jbang-eip-builder/test-project-workspace/FAKER/faker-db/financial
FAKER_TEMPLATES_DIR=/home/pratyush/software/jbang-eip-builder/test-project-workspace/FAKER/templates
MAPPING_DIR=/home/pratyush/software/jbang-eip-builder/test-project-workspace/mappings
VALIDATOR_DIR=/home/pratyush/software/jbang-eip-builder/test-project-workspace/validator
WORKSPACE_ROOT_DIR=/home/pratyush/software/jbang-eip-builder/test-project-workspace
camel.jbang.platform-http.port=9999
dlq.uri=stub\:jms\:queue\:DLQ
enricher.customer.service=stub\:direct\:fetch-customer
http.downstream.endpoint=stub\:http\:downstream-service/api
http.orders.endpoint=stub\:http\:api.example.com/orders
ibmmq-endpoint=stub\:jms\:queue\:IBMMQ.Q
ibmmq-sink=stub\:ibmmq-sink
ibmmq-source=stub\:ibmmq-source
ibmmq.audit.trail=stub\:jms\:queue\:audit.trail
ibmmq.dlq.queue=stub\:jms\:queue\:DLQ
ibmmq.queue=stub\:IBMMQ.INBOUND.Q
ibmmq.reply.queue=stub\:jms\:queue\:REPLY.Q
ibmmq.request.queue=stub\:jms\:queue\:REQUEST.Q
ibmmq.request.uri=stub\:jms\:queue\:REQUEST.Q
ibmmq.xa.request=stub\:jms\:queue\:XA.REQUEST
kafka.orders.endpoint=stub\:kafka\:topic\:orders
kafka.orders.uri=stub\:kafka\:topic\:orders
mongodb.audit.transactions=stub\:mongodb\:myDb?consumerType\=changeStream&database\=audit&collection\=transactions
mongodb.orders.endpoint=stub\:mongodb\:cameldb?operation\=insert
mongodb.orders.uri=stub\:mongodb\:cameldb?operation\=insert
notify.email.queue=stub\:jms\:queue\:NOTIFY.EMAIL
notify.sms.queue=stub\:jms\:queue\:NOTIFY.SMS
wiretap.audit.uri=stub\:jms\:queue\:audit.trail
