apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: kamelet-studio-ibmmq-xa-source
  labels:
    camel.apache.org/kamelet.type: "source"
  annotations:
    camel.apache.org/kamelet.title: "Kamelet Studio IBM MQ XA Source"
    camel.apache.org/kamelet.version: "1.0.0"
spec:
  definition:
    title: "Kamelet Studio IBM MQ XA Source"
    description: "Consumes messages from IBM MQ using an XA connection pool enlisted in a JTA transaction."
    required:
      - queuename
    type: object
    properties:
      queuename:
        type: string
      hostname:
        type: string
        default: "localhost"
      port:
        type: integer
        default: 1414
      queuemanager:
        type: string
        default: "QM1"
      channel:
        type: string
        default: "DEV.APP.SVRCONN"
      sslciphersuite:
        type: string
        default: ""
      truststorepath:
        type: string
        default: ""
      truststorepassword:
        type: string
        format: password
      keystorepath:
        type: string
        default: ""
      keystorepassword:
        type: string
        format: password
  template:
    beans:
      - name: sslFactory
        type: "#class:com.routebuilder.kameletstudio.core.lib.crypto.KameletStudioSslSocketFactory"
        properties:
          trustStorePath: '{{truststorepath}}'
          trustStorePassword: '{{truststorepassword}}'
          keyStorePath: '{{keystorepath}}'
          keyStorePassword: '{{keystorepassword}}'
      - name: mqXAConnectionFactory
        type: "#class:com.ibm.mq.jakarta.jms.MQXAConnectionFactory"
        properties:
          hostName: '{{hostname}}'
          port: '{{port}}'
          queueManager: '{{queuemanager}}'
          channel: '{{channel}}'
          sslCipherSuite: '{{sslciphersuite}}'
          sslSocketFactory: '#bean:{{sslFactory}}'
      - name: mqXAPoolFactory
        type: "#class:org.messaginghub.pooled.jms.JmsPoolXAConnectionFactory"
        properties:
          connectionFactory: '#bean:mqXAConnectionFactory'
          transactionManager: '#bean:jtaTxManager'
          maxConnections: 5
    from:
      uri: "jms:queue:{{queuename}}"
      parameters:
        connectionFactory: "#bean:{{mqXAPoolFactory}}"
        transactionManager: "#bean:jtaTxManager"
        transacted: false
        cacheLevelName: "CACHE_NONE"
      steps:
        - to: "kamelet:sink"
