apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: ibmmq-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
  annotations:
    camel.apache.org/kamelet.title: "Kamelet Studio IBM MQ Sink"
    camel.apache.org/kamelet.version: "1.0.0"
spec:
  definition:
    title: "Kamelet Studio IBM MQ Sink"
    description: "Publishes messages to IBM MQ with SSL, mTLS, and Kerberos support."
    required:
      - queuename
    type: object
    properties:
      queuename:
        type: string
      hostname:
        type: string
        default: "localhost"
      port:
        type: integer
        default: 1414
      queuemanager:
        type: string
        default: "QM1"
      channel:
        type: string
        default: "DEV.APP.SVRCONN"
      username:
        type: string
        default: ""
      password:
        type: string
        format: password
        default: ""
      sslciphersuite:
        type: string
        default: ""
      sslPeerName:
        type: string
        default: ""
      sslFipsRequired:
        type: boolean
        default: false
      transportType:
        type: integer
        default: 1
      trustStorePath:
        type: string
        default: ""
      trustStorePassword:
        type: string
        format: password
        default: ""
      keyStorePath:
        type: string
        default: ""
      keyStorePassword:
        type: string
        format: password
        default: ""
      maxConnections:
        type: integer
        default: 5
      idleTimeout:
        type: integer
        default: 30000
  template:
    beans:
      - name: sslFactory
        type: "#class:com.routebuilder.kameletstudio.core.lib.crypto.KameletStudioSslSocketFactory"
        properties:
          trustStorePath: '{{trustStorePath}}'
          trustStorePassword: '{{trustStorePassword}}'
          keyStorePath: '{{keyStorePath}}'
          keyStorePassword: '{{keyStorePassword}}'
      - name: mqConnectionFactory
        type: "#class:com.ibm.mq.jakarta.jms.MQConnectionFactory"
        properties:
          hostName: '{{hostname}}'
          port: '{{port}}'
          queueManager: '{{queuemanager}}'
          channel: '{{channel}}'
          sslciphersuite: '{{sslciphersuite}}'
          sslSocketFactory: '#bean:{{sslFactory}}'
          sslPeerName: '{{sslPeerName}}'
          sslFipsRequired: '{{sslFipsRequired}}'
          userName: '{{username}}'
          password: '{{password}}'
          transportType: '{{transportType}}'
      - name: mqPoolFactory
        type: "#class:org.messaginghub.pooled.jms.JmsPoolConnectionFactory"
        properties:
          connectionFactory: '#bean:{{mqConnectionFactory}}'
          maxConnections: '{{maxConnections}}'
          connectionIdleTimeout: '{{idleTimeout}}'
    from:
      uri: "kamelet:source"
      steps:
        - to:
            uri: "jms:queue:{{queuename}}"
            parameters:
              connectionFactory: "#bean:{{mqPoolFactory}}"
