apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: kamelet-studio-log-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
  annotations:
    camel.apache.org/kamelet.title: "Kamelet Studio Log Sink"
    camel.apache.org/kamelet.version: "1.0.0"
spec:
  definition:
    title: "Log Sink"
    description: "Logs the incoming message body and headers."
    properties:
      showHeaders:
        type: boolean
        default: false
        description: "Show headers in output."
  template:
    from:
      uri: "kamelet:source"
      steps:
        - log:
            message: "Incoming Body: ${body}"
            showHeaders: "{{showHeaders}}"
