apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: kamelet-studio-mongodb-source
  labels:
    camel.apache.org/kamelet.type: "source"
  annotations:
    camel.apache.org/kamelet.title: "Kamelet Studio MongoDB Source"
    camel.apache.org/kamelet.version: "1.0.0"
spec:
  definition:
    title: "Kamelet Studio MongoDB Source"
    description: "Consumes real-time database modifications using Change Streams or Tailable Cursors."
    required:
      - database
      - collection
    type: object
    properties:
      connectionBean:
        type: string
        default: "mongoClient"
      database:
        type: string
      collection:
        type: string
      consumerType:
        type: string
        default: "changeStreams"
        enum: [ "changeStreams", "tailable" ]
      streamFilter:
        type: string
        description: "Aggregation pipeline JSON filter to match criteria (e.g. '[{\"$match\": {\"fullDocument.status\": \"CRITICAL\"}}]')."
        default: ""
  template:
    from:
      uri: "mongodb:{{connectionBean}}?database={{database}}&collection={{collection}}&consumerType={{consumerType}}&streamFilter={{?streamFilter}}&createCollection=true"
      steps:
        - to: "kamelet:sink"
