apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: kamelet-studio-solace-xa-source
  labels:
    camel.apache.org/kamelet.type: "source"
  annotations:
    camel.apache.org/kamelet.title: "Kamelet Studio Solace XA Source"
    camel.apache.org/kamelet.version: "1.0.0"
spec:
  definition:
    title: "Kamelet Studio Solace XA Source"
    description: "Consumes messages from Solace using an XA connection pool managed by JTA."
    required:
      - queuename
      - host
      - vpn
    type: object
    properties:
      queuename:
        type: string
      host:
        type: string
        default: "smfs://localhost:55443"
      vpn:
        type: string
        default: "default"
      username:
        type: string
      password:
        type: string
        format: password
  template:
    beans:
      - name: solaceXAConnectionFactory
        type: "#class:com.solacesystems.jms.SolJmsUtility"
        factory-method: "createXAConnectionFactory"
        properties:
          host: '{{host}}'
          vpn: '{{vpn}}'
          username: '{{username}}'
          password: '{{password}}'
      - name: solaceXAPoolFactory
        type: "#class:org.messaginghub.pooled.jms.JmsPoolXAConnectionFactory"
        properties:
          connectionFactory: '#bean:{{solaceXAConnectionFactory}}'
          transactionManager: '#bean:jtaTxManager'
          maxConnections: 5
    from:
      uri: "jms:queue:{{queuename}}"
      parameters:
        connectionFactory: "#bean:{{solaceXAPoolFactory}}"
        transactionManager: "#bean:jtaTxManager"
        transacted: false
        cacheLevelName: "CACHE_NONE"
      steps:
        - to: "kamelet:sink"
