apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: kamelet-studio-mongodb-action
  labels:
    camel.apache.org/kamelet.type: "action"
  annotations:
    camel.apache.org/kamelet.title: "Kamelet Studio MongoDB Action"
    camel.apache.org/kamelet.version: "1.0.0"
spec:
  definition:
    title: "Kamelet Studio MongoDB Action"
    description: "Executes dynamic queries, updates, aggregations, or bulk operations mid-route."
    required:
      - database
      - collection
    type: object
    properties:
      connectionBean:
        type: string
        default: "mongoClient"
      database:
        type: string
      collection:
        type: string
      operation:
        type: string
        default: "findOneByQuery"
        enum: [ "findOneByQuery", "findAll", "update", "remove", "aggregate", "bulkWrite" ]
      upsert:
        type: boolean
        default: false
      filter:
        type: string
        description: "Inline query criteria filter (e.g. '{\"_id\": \"123\"}') to override body content."
        default: ""
  template:
    from:
      uri: "kamelet:source"
      steps:
        - setHeader:
            name: "CamelMongoDbCriteria"
            simple: "{{?filter}}"
        - setHeader:
            name: "CamelMongoDbUpsert"
            simple: "{{upsert}}"
        - to: "mongodb:{{connectionBean}}?database={{database}}&collection={{collection}}&operation={{operation}}"
