apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: kamelet-studio-solace-source
  labels:
    camel.apache.org/kamelet.type: "source"
  annotations:
    camel.apache.org/kamelet.title: "Kamelet Studio Solace Source"
    camel.apache.org/kamelet.version: "1.0.0"
spec:
  definition:
    title: "Kamelet Studio Solace Source"
    description: "Consumes messages from Solace PubSub+ queue using SMF or SMFS TLS."
    required:
      - queuename
      - host
      - vpn
    type: object
    properties:
      queuename:
        type: string
      host:
        type: string
        default: "smf://localhost:55555"
      vpn:
        type: string
        default: "default"
      username:
        type: string
      password:
        type: string
        format: password
      transacted:
        type: boolean
        default: true
      ssltruststorepath:
        type: string
      ssltruststorepassword:
        type: string
        format: password
      sslkeystorepath:
        type: string
      sslkeystorepassword:
        type: string
        format: password
  template:
    beans:
      - name: solaceConnectionFactory
        type: "#class:com.solacesystems.jms.SolJmsUtility"
        factory-method: "createConnectionFactory"
        properties:
          host: '{{host}}'
          vpn: '{{vpn}}'
          username: '{{username}}'
          password: '{{password}}'
          sslTrustStore: '{{?ssltruststorepath}}'
          sslTrustStorePassword: '{{?ssltruststorepassword}}'
          sslKeyStore: '{{?sslkeystorepath}}'
          sslKeyStorePassword: '{{?sslkeystorepassword}}'
      - name: solacePoolFactory
        type: "#class:org.messaginghub.pooled.jms.JmsPoolConnectionFactory"
        properties:
          connectionFactory: '#bean:{{solaceConnectionFactory}}'
          maxConnections: 5
    from:
      uri: "jms:queue:{{queuename}}"
      parameters:
        connectionFactory: "#bean:{{solacePoolFactory}}"
        transacted: "{{transacted}}"
      steps:
        - to: "kamelet:sink"
